spring:
  datasource:
    url: jdbc:h2:mem:testdb
    # url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/testdata


application:
  security:
    username: ${API_USER_NAME:admin}
    password: ${API_USER_PASSWORD:admin}

  path:
    ping: /ping
    ecommerce-price-service: /ecommerce-price-service/api/prices


server:
  servlet:
    context-path: /ecommerce-price-service




